#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export PUPIL_HYBRID_ENABLED="${PUPIL_HYBRID_ENABLED:-1}"
export PUPIL_HYBRID_DVS_PROCESS="${PUPIL_HYBRID_DVS_PROCESS:-1}"
export PUPIL_HYBRID_DVS_PROCESS_INLINE="${PUPIL_HYBRID_DVS_PROCESS_INLINE:-1}"
export PUPIL_HYBRID_FAST_BINAREP="${PUPIL_HYBRID_FAST_BINAREP:-1}"
export PUPIL_HYBRID_TDTRACKER_MODE="${PUPIL_HYBRID_TDTRACKER_MODE:-graph}"
export PUPIL_HYBRID_GRAPH_RESULT="${PUPIL_HYBRID_GRAPH_RESULT:-1}"
export PUPIL_HYBRID_ASYNC_RESULT="${PUPIL_HYBRID_ASYNC_RESULT:-1}"
export PUPIL_HYBRID_ASYNC_RESULT_SLOTS="${PUPIL_HYBRID_ASYNC_RESULT_SLOTS:-8}"
export PUPIL_HYBRID_CPP_BINAREP="${PUPIL_HYBRID_CPP_BINAREP:-1}"
export PUPIL_HYBRID_CONF_THRESHOLD="${PUPIL_HYBRID_CONF_THRESHOLD:-0.3}"
export PUPIL_HYBRID_DVS_EYE_ID="${PUPIL_HYBRID_DVS_EYE_ID:-0}"
export PUPIL_HYBRID_PROFILE_SYNC="${PUPIL_HYBRID_PROFILE_SYNC:-0}"
export PUPIL_HYBRID_DVS_VIZ="${PUPIL_HYBRID_DVS_VIZ:-0}"
export PUPIL_HYBRID_LATENCY_LOG="${PUPIL_HYBRID_LATENCY_LOG:-0}"

NATIVE_LIBRARY="${PROJECT_DIR}/pupil_src/shared_modules/pupil_detector_plugins/_native_binarep.so"
if [[ "${PUPIL_HYBRID_CPP_BINAREP}" == "1" && ! -f "${NATIVE_LIBRARY}" ]]; then
  "${PROJECT_DIR}/pupil_src/shared_modules/pupil_detector_plugins/build_native_binarep.sh"
fi

exec "${PUPIL_PYTHON:-python3}" "${PROJECT_DIR}/pupil_src/main.py" "$@"
